---

- name: Clone Git repository
  git:
    repo: git@github.com/edf-hpc/slurm-web.git
    version: master
    dest: /slurm-web
    
- name: build the image
  command: docker build -t slurm-web ./site

- name: run the site in a docker container
   docker:
    name: slurm-web
    image: "slurm-web"
    state: reloaded
        
    
