---

- name: create build directory
  file:
    path: /root/slurm-web-build
    state: directory
    recurse: yes 

- name: Clone Git repository
  git:
    repo: https://github.com/edf-hpc/slurm-web.git
    version: master
    dest: /root/slurm-web-build
    
- name: Build container
  command: docker build -t slurm-web /root/slurm-web-build
    
- name: Create container
  command: docker create slurm-web
  
- name: Run docker container
  command: docker run slurm-web:latest
  
 

   
   

    
