---

- name: create build directory
  file:
    path: /slurm-web/docker/container
    state: directory
    owner: root
    group: root
    mode: '0755'
    recurse: yes 

- name: Clone Git repository
  git:
    repo: https://github.com/edf-hpc/slurm-web.git
    version: master
    dest: /slurm-web/docker/container
    
- name: Build container image
  command: docker build -t slurm-web ./slurm-web/docker/container
  
- name: run the site in a docker container
   docker:
     name: slurm-web
     image: "slurm-web"
     state: reloaded
     publish_all_ports: yes
     use_tls: encrypt

 

   
   

    
