---

- name: create build directory
  file:
        path: /root/slurm-web
        state: directory
        owner: root
        group: root
        mode: '0755'

- name: Clone Git repository
  git:
    repo: https://github.com/edf-hpc/slurm-web.git
    version: master
    dest: /root/slurm-web/dockerfile 
    owner: root     
    group: root
    mode: '0644'
   
 - name: build container image
   docker_image:
        name: slurm-web container
        build:
          path: /root/slurm-web/dockerfile
          source: build
        state: present
    
