---

- name: create build directory
  file:
    path: /slurm-web
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Clone Git repository
  git:
    repo: https://github.com/edf-hpc/slurm-web.git
    version: master
    dest: /slurm-web/dockerfile 
    
- name: Build an image and push
    docker_image:
        build:
          path: /slurm-web
        name: docker-file/slurm-web
        tag: v1
        source: build
      delegate_to: 127.0.0.1
  


   
   

    
