---

- name: Clone Git repository
  git:
    repo: https://github.com/edf-hpc/slurm-web.git
    version: master
    dest: /slurm-web 

- name: Build docker container
  docker:
    name: slurm-web
    command: docker build -t slurm-web ./site
    image: "slurm-web"
    state: present
        
    
