---

- name: create build directory
  file:
    path: /slurm-web/docker/container
    state: directory
    recurse: yes 

- name: Clone Git repository
  git:
    repo: https://github.com/edf-hpc/slurm-web.git
    version: master
    dest: /slurm-web/docker/container
    
- name: Build container
  build_container: 
    name: slurm-web
    tag: latest
    
    
- name: Create container
  command: docker create slurm-web
  
- name: Run docker container
  command: docker run slurm-web:latest
  
 

   
   

    
