---

- name: create build directory
  file:
    path: /slurm-web/dockerfile
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Clone Git repository
  git:
    repo: https://github.com/edf-hpc/slurm-web.git
    version: master
    dest: /slurm-web
    
- name: Build container image
  command: docker build -t slurm-web --file= slurm-web
 

   
   

    
