---

- name: create build directory
  file:
    path: /root/slurm-web
    state: directory
    recurse: yes 

- name: Clone Git repository
  git:
    repo: https://github.com/edf-hpc/slurm-web.git
    version: master
    dest: /root/slurm-web
    
- name: Build container
  command: docker build -t slurm-web /root/slurm-web/docker/container
    
- name: Create container
  command: docker create slurm-web
  
- name: Run docker container
  command: /root/slurm-web/docker/run/run.sh
 
- name: docker cron setup
  cron: 
    name: run container on reboot
    special_time: reboot
    job: /root/slurb-web/docker/run/run.sh
    state: present
  
 

   
   

    
