---
- name: systemd reload
  systemd:
    daemon_reload: yes

- name: restart munge
  service:
    name: munge
    state: restarted

- name: reload slurmdbd
  service:
    name: "{{ slurmdbd_service_name }}"
    state: reloaded
  when: "'slurmdbdservers' in group_names or 'dbd' in slurm_roles"

- name: reload slurmd
  service:
    name: "{{ slurmd_service_name }}"
    state: reloaded
  when: "'slurmexechosts' in group_names or 'exec' in slurm_roles"

- name: restart slurmd
  service:
    name: "{{ slurmd_service_name }}"
    state: restarted
  when: "'slurmexechosts' in group_names or 'exec' in slurm_roles"
